export const servicosDisponiveis = [
  "Troca de Óleo",
  "Alinhamento",
  "Balanceamento",
  "Troca de Pneus",
  "Sistema de Freios",
  "Sistema Elétrico",
  "Ar Condicionado",
  "Suspensão",
  "Motor",
  "Transmissão",
  "Injeção Eletrônica",
  "Diagnóstico Eletrônico",
  "Funilaria e Pintura",
  "Vidraçaria",
  "Som Automotivo",
];

export const diasSemana = [
  { key: "segunda", label: "Segunda-feira" },
  { key: "terca", label: "Terça-feira" },
  { key: "quarta", label: "Quarta-feira" },
  { key: "quinta", label: "Quinta-feira" },
  { key: "sexta", label: "Sexta-feira" },
  { key: "sabado", label: "Sábado" },
  { key: "domingo", label: "Domingo" },
];

export const defaultFormValues = {
  nomeOficina: "",
  cnpj: "",
  email: "",
  telefone: "",
  whatsapp: "",
  cep: "",
  rua: "",
  numero: "",
  complemento: "",
  bairro: "",
  cidade: "",
  estado: "",
  senha: "",
  confirmaSenha: "",
  listaDeServicos: [],
  mechanicType: { value: "", label: "" },
  fotos: [],
  horarioAtendimento: {
    segunda: { inicio: "08:00", fim: "18:00", aberto: true },
    terca: { inicio: "08:00", fim: "18:00", aberto: true },
    quarta: { inicio: "08:00", fim: "18:00", aberto: true },
    quinta: { inicio: "08:00", fim: "18:00", aberto: true },
    sexta: { inicio: "08:00", fim: "18:00", aberto: true },
    sabado: { inicio: "08:00", fim: "12:00", aberto: true },
    domingo: { inicio: "08:00", fim: "18:00", aberto: false },
  },
  descricao: "",
};
